### ISSUE TITLE
Is there any way to hide country name and country code

### ISSUE THREAD

**Issue by chetan-sharma-newput** [alien9996/react-native-country-picker#1]
Please check the screenshot this is how it is looking in the ios simulator iPhone 12 pro, and android is having the worst modal view.
IOS :-
![simulator_screenshot_F7FBD31A-2C5C-404A-9D5A-94794694F442](https://user-images.githubusercontent.com/59158878/113691724-5fe09700-96ea-11eb-8551-8d179552ec0b.png)
Android :-
![Screenshot_20210406-151747](https://user-images.githubusercontent.com/59158878/113692651-5e639e80-96eb-11eb-9036-9d8ea3432496.png)

                    
```
 <CountryPicker
							enable={true}
							darkMode={false}
							countryCode={this.state.countryCode}
							showFlag={true}
							showCallingCode={true}
							showCountryName={false}
							showCountryCode={false}
							onSelectCountry={(data) => {
								this.onSelect(data)
								console.log("DATA", data);
							}}
							onOpen={() => {

							}}
							onClose={() => {

							}}
							containerStyle={{
								flagStyle: { fontSize: 25 },
								callingCodeStyle: styles.textStyle,
								countryCodeStyle: styles.textStyle,
								countryNameStyle: {},
							}}
							modalStyle={{
								container: {},
								searchStyle: {},
								tileStyle: {},
								itemStyle: {
									itemContainer: { alignItems: 'center' },
									flagStyle: {},
									countryCodeStyle: {},
									countryNameStyle: {},
									callingNameStyle: {flex:1},
								},
							}}
							title={"Select your country"}
							searchPlaceholder={"Search"}
							showCloseButton={true}
							showModalTitle={true}
						/>

```

**Comment by alien9996** [comment]
Thanks for your feedback! I will update in the next version! Please wait a few hours!

**Comment by chetan-sharma-newput** [comment]
I am facing this issue on every IOS simulator and android too. Thank you in advance.

**Comment by alien9996** [comment]
I have updated to the new version 1.1.0. You can use the new version and customize it to your liking.

containerConfig={{
      showFlag: true,
      showCallingCode: true,
      showCountryName: true,
      showCountryCode: true
  }}
  modalConfig={{
      showFlag: true,
      showCallingCode: true,
      showCountryName: false,
      showCountryCode: false
  }}
                    
Please review the Readme.md file to see the latest updates. Thanks!

**Comment by alien9996** [comment]
![simulator_screenshot_CDA7024B-2DC7-4F45-B628-617EAA1A73DE](https://user-images.githubusercontent.com/45571280/113704123-f2426400-9705-11eb-85f9-fa47a8301645.png)

**Comment by chetan-sharma-newput** [comment]
> I have updated to the new version 1.1.0. You can use the new version and customize it to your liking.
> 
> containerConfig={{
> showFlag: true,
> showCallingCode: true,
> showCountryName: true,
> showCountryCode: true
> }}
> modalConfig={{
> showFlag: true,
> showCallingCode: true,
> showCountryName: false,
> showCountryCode: false
> }}
> 
> Please review the Readme.md file to see the latest updates. Thanks!

Ok, I will check that, thank you so much it will really help me.

**Comment by chetan-sharma-newput** [comment]
![Simulator Screen Shot - iPhone 12 Pro - 2021-04-06 at 17 40 43](https://user-images.githubusercontent.com/59158878/113708801-501f7d80-96ff-11eb-887d-b12bedd66e74.png)

Now UI is not looking good, The name of the country "United Arab Emirates" should be in one line, you can place the countryName in the center when showCountryCode is false. I tried to give a custom style but did not work.


And when I make everything true then I face the old problem again.
```
modalConfig={{
showFlag: true,
showCallingCode: true,
showCountryName: false,
showCountryCode: false
}}

```

please check.

**Comment by alien9996** [comment]
I provide an option modalStyle to make a style change to a component in the modal.
You can do the following to put the country name on one line and can add other properties if you want to change the child elements.

modalStyle={{
      itemStyle: {
          itemContainer: {},
          flagStyle: {},
          countryCodeStyle: {},
          countryNameStyle: { width: undefined },
          callingNameStyle: {},
      },
  }}
