### ISSUE TITLE
Get current selected country data

### ISSUE THREAD

**Issue by emrecanozkok** [alien9996/react-native-country-picker#3]
I can set up with default country code but i need to get current selected country info. how can i do this or how i can trigger on country change event externally.

**Comment by emrecanozkok** [comment]
im added onInit event for first init because when i not define default country code, the component detect my country and select but there is no event to get this detected country.if you can give me a permission to push feature branch i can push or you can add.

**Comment by alien9996** [comment]
Thank you ! I have merged your revision into master! If you have any other comments, please share more!
