### ISSUE TITLE
Jordan country code is wrong

### ISSUE THREAD

**Issue by emrecanozkok** [alien9996/react-native-country-picker#6]
jordan country code is wrong
its need to be 

`{
      "code": "JO",
      "unicode": "U+1F1EF U+1F1F4",
      "name": "Jordan",
      "emoji": "🇯🇴",
      "callingCode": "962"
}`

**Comment by emrecanozkok** [comment]
#7 fixed in pull request

**Comment by alien9996** [comment]
Thank you ! I have merged your revision into master!
